spring.application.name=helpMeTravel
spring.ai.deepseek.api-key=sk-be075641ba534719ab9e723b5b9550ba
spring.ai.deepseek.chat.options.model=deepseek-chat
spring.ai.deepseek.chat.options.temperature=0.8

spring.data.mongodb.uri=mongodb+srv://simannathsn:tbRijSL3eWjmGvOr@cluster0.7b3yxbn.mongodb.net/UserReview?retryWrites=true&w=majority&appName=Cluster0
